name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  test-pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: prerelease
      url: https://test.pypi.org/p/pyverbs
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build package
        run: |
          uv build --wheel

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
