name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment:
      name: prerelease
      url: https://test.pypi.org/p/pyverbs
    steps:
      - run: |
          sudo apt-get install -y \
              build-essential \
              cmake \
              gcc \
              libudev-dev \
              libnl-3-dev \
              libnl-route-3-dev \
              ninja-build \
              pkg-config \
              valgrind

      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build package
        run: |
          uv build --wheel

      - uses: actions/upload-artifact@v4
        with:
          name: python-wheels-ubuntu-latest
          path: dist

  test-pypi-publish:
    name: Publish release to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prerelease
      url: https://test.pypi.org/p/pyverbs
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-wheels-ubuntu-latest
          path: dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          verbose: true
          repository-url: https://test.pypi.org/legacy/
